export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_LOGOUT = 'USER_LOGIN_LOGOUT';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const LOAN_TAKE_REQUEST = 'LOAN_TAKE_REQUEST';
export const LOAN_TAKE_SUCCESS = 'LOAN_TAKE_SUCCESS';
export const LOAN_TAKE_FAIL = 'LOAN_TAKE_FAIL';

export const LOAN_ADD_VALUES = 'LOAN_ADD_VALUES';
export const LOAN_RESET_VALUES = 'LOAN_RESET_VALUES';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_';

export const ALERT_ADD = 'ALERT_ADD';
export const ALERT_REMOVE = 'ALERT_REMOVE';
