export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_LOGOUT = 'USER_LOGIN_LOGOUT';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_UPDATE_PASSWORD_REQUEST = 'USER_UPDATE_PASSWORD_REQUEST';
export const USER_UPDATE_PASSWORD_SUCCESS = 'USER_UPDATE_PASSWORD_SUCCESS';
export const USER_UPDATE_PASSWORD_FAIL = 'USER_UPDATE_PASSWORD_FAIL';

export const LOAN_TAKE_REQUEST = 'LOAN_TAKE_REQUEST';
export const LOAN_TAKE_SUCCESS = 'LOAN_TAKE_SUCCESS';
export const LOAN_TAKE_RESET = 'LOAN_TAKE_RESET';
export const LOAN_TAKE_FAIL = 'LOAN_TAKE_FAIL';
export const LOAN_TAKE_CLEAR = 'LOAN_TAKE_CLEAR';

export const LOAN_LIST_REQUEST = 'LOAN_LIST_REQUEST';
export const LOAN_LIST_SUCCESS = 'LOAN_LIST_SUCCESS';
export const LOAN_LIST_FAIL = 'LOAN_LIST_FAIL';
export const LOAN_LIST_CLEAR = 'LOAN_LIST_CLEAR';

export const LOAN_PAY_REQUEST = 'LOAN_PAY_REQUEST';
export const LOAN_PAY_SUCCESS = 'LOAN_PAY_SUCCESS';
export const LOAN_PAY_FAIL = 'LOAN_PAY_FAIL';

export const LOAN_DETAILS_REQUEST = 'LOAN_DETAILS_REQUEST';
export const LOAN_DETAILS_SUCCESS = 'LOAN_DETAILS_SUCCESS';
export const LOAN_DETAILS_FAIL = 'LOAN_DETAILS_FAIL';

export const NEW_LOAN_SETTINGS = 'NEW_LOAN_SETTINGS';

export const ALERT_ADD = 'ALERT_ADD';
export const ALERT_REMOVE = 'ALERT_REMOVE';
