export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_LOGOUT = 'USER_LOGIN_LOGOUT';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const LOAN_TAKE_REQUEST = 'LOAN_TAKE_REQUEST';
export const LOAN_TAKE_SUCCESS = 'LOAN_TAKE_SUCCESS';
export const LOAN_TAKE_FAIL = 'LOAN_TAKE_FAIL';

export const LOAN_LIST_REQUEST = 'LOAN_LIST_REQUEST';
export const LOAN_LIST_SUCCESS = 'LOAN_LIST_SUCCESS';
export const LOAN_LIST_ADD = 'LOAN_LIST_ADD';
export const LOAN_LIST_FAIL = 'LOAN_LIST_FAIL';

export const NEW_LOAN_SETTINGS = 'NEW_LOAN_SETTINGS';

export const ALERT_ADD = 'ALERT_ADD';
export const ALERT_REMOVE = 'ALERT_REMOVE';
